/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DisplayValues: typeof import('./components/DisplayValues.vue')['default']
    EventList: typeof import('./components/EventList.vue')['default']
    FormInputFields: typeof import('./components/FormInputFields.vue')['default']
    LocalStorageState: typeof import('./components/LocalStorageState.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./components/Test.vue')['default']
  }
}
